### ISSUE TITLE
[Feature request] Add an abstract power consumption recipe

### ISSUE THREAD

**Issue by Saklad5** [ShadowTheAge/yafc#113] opened 2021-04-26 22:46 UTC
Space Exploration’s core miners are not something I ever expect to be supported entirely by this program: they produce a consistent amount of core fragments, but the rate is determined by a relatively complicated formula that includes SE-specific surface properties and the number of active core miners on said surface.

I feel the best method to bypass this lack of support is creating a nested table and configure the amount of core fragments produced that way. However, this causes a problem: because YAFC has the number of core miners necessary to produce that quantity wrong, the amount of power being consumed is also wrong. As each core miner requires 50MW, this is a significant discrepancy.

To fix that, I’d like a fake “dummy” recipe that consumes/adds an arbitrary amount of power. By adding such a recipe into the nested table I described above, I’d be able to change the power draw to reflect the reality.

**Comment by ShadowTheAge** [comment] 2021-04-26 22:57
You can add desired products inside (or outside) nested tables. You can add desired power like that. That will also create a link so add it at the level where you have power production.

**Comment by ShadowTheAge** [comment] 2021-05-01 10:57
I will close the issue now
There may be improvements for this scenario if YAFC could capture non-matched links. Current behaviour of not-matching is by design, but I may change that, there is another issue on that case https://github.com/ShadowTheAge/yafc/issues/95

Otherwise, "abstract production / consumption" is exactly what desired products are

**Closed by ShadowTheAge** 2021-05-01 10:57 UTC
Labels: enhancement
