### ISSUE TITLE
[BUG] Py is weird about mining tar/crude oil/natural gas

### ISSUE THREAD

**Issue by Emerassi** [ShadowTheAge/yafc#119] opened 2021-05-25 03:33 UTC
YAFC version .5.7.1

I'm using the full py suite and some QoL mods.  Currently in Py you slap down something like a Tar extractor on a 'Bitumen Seep'.  Pump it with drilling fluid and eventually it turns into an actual Tar extractor that just gives Tar in exchange for electricity.  I have gone into the dependency explorer and attempted to enable this recipe but I'm only allowed to flag it as accessible and not as automatable.  As a result, YAFC doesn't use it when deciding how much of my Tar should come from this source, or modify the YAFC cost based on this recipe.  Not at all sure what the best fix would be here.  It would be cool if it 'just worked' without flagging anything.  It would also be cool if it was possible to flag it as automatable instead of just accessible.

[YAFCNewSave.zip](https://github.com/ShadowTheAge/yafc/files/6536266/YAFCNewSave.zip)

**Comment by ShadowTheAge** [comment] 2021-05-25 09:39
Incorrectly flagging things as automatable will break yafc cost completely, even for unrelated stuff (there will be infinities and NaNs everywhere), so I can't add that option. "Automatable" basically means "have finite yafc cost". Things like vanilla wood doesn't have finite yafc cost.

I have specifically decided that I wouldn't "code" mod-specific features because mods change and new mods appear all the time. There is however an option for mod-makers to mark things accessible.

I will look at what to do with your save later. I think you should mark the resource patch that Py uses internally to mine from as accessible instead.

**Comment by Emerassi** [comment] 2021-05-25 17:26
I think I understand what you're saying regarding wood, where there's no
recipe to make wood but you can still get it (in vanilla). I can't tell if
that logic carries over to tar in Py where there's dozens of recipes that
do make Tar just fine, and there's just one recipe that is misbehaving
because the mod makers made it weird.

I'm not really clear on if I'm doing what you suggested correctly so I'm
going to give it a quick shot with some screenshots so hopefully if I
blundered on something obvious you'll know where I went wrong.

Before any changes I see this recipe in the Never Enough Items Explorer
(the second one):
[image: image.png]

If I were to mark the resource patch accessible, I assume that would be
this:

[image: image.png]
I click to manually mark as accessible:
[image: image.png]

The recipe now shows up as accessible in the Never Enough Items Explorer,
but doesn't have any blue bar on it to indicate how much of my production
would come from here and the YAFC cost also doesn't change:
[image: image.png]
Anyways, it seemed like getting those 2 things to behave correctly would
require this to be flagged as automatable instead of just accessible but I
wasn't sure (I compared the Tar pit mining (Mechanics) to Iron Ore mining
(Mechanics) and accessible vs automated seemed like the only difference).
You mentioned there's an option for mod-makers to mark things as
accessible, would that get the same results as my manual flag?  Is it
possible to get it marked as automatable instead?  I don't mind attempting
that myself if it's possible.

Thanks

**Comment by ShadowTheAge** [comment] 2021-05-27 12:28
Unfortunaly there are no images in your post. You may need to reply on github

**Comment by Emerassi** [comment] 2021-05-27 17:28
>.<  Ok trying again with replying on github!

Before any changes I see this recipe in the Never Enough Items Explorer
(the second one):
![image](https://user-images.githubusercontent.com/78173681/119870382-2bad7980-bed6-11eb-8648-86bc641ce3eb.png)



If I were to mark the resource patch accessible, I assume that would be
this:
![image](https://user-images.githubusercontent.com/78173681/119870396-2f410080-bed6-11eb-99ee-661c916b6a30.png)


I click to manually mark as accessible:
![image](https://user-images.githubusercontent.com/78173681/119870414-3405b480-bed6-11eb-9964-6afd0e23fd60.png)


The recipe now shows up as accessible in the Never Enough Items Explorer,
but doesn't have any blue bar on it to indicate how much of my production
would come from here and the YAFC cost also doesn't change:
![image](https://user-images.githubusercontent.com/78173681/119870439-39fb9580-bed6-11eb-94f8-178b3b4d16c2.png)

**Comment by ShadowTheAge** [comment] 2021-05-28 16:17
Well, there is no blue bar because YAFC thinks that mining tar pit is not the best way to get tar. It was able to satisfy its tar needs with other recipes. And the cost doesn't change because of that - tar was already basically a byproduct and pretty cheap

**Comment by ShadowTheAge** [comment] 2021-05-28 16:27
just to confirm, does yafc show that recipe "tar mining" (not the tar pits) are automatable after you makr tar pits as accessible?

**Comment by Emerassi** [comment] 2021-05-28 17:34
Ok I'll give it a try.

Tar pit is marked as accessible:
![image](https://user-images.githubusercontent.com/78173681/120021530-07b66a80-bfa0-11eb-99d4-228e9dfe0ef6.png)

Tar pit mining is -not- automatable after that:
![image](https://user-images.githubusercontent.com/78173681/120021652-33d1eb80-bfa0-11eb-959c-c9b65132ba3d.png)

**Comment by ShadowTheAge** [comment] 2021-05-28 19:01
I have tried your save and the behaviour does not reproduce. I may need your project also
Oh, and some things recalculate only when you close all temporary screens like dependency explorer. Maybe you weren't doing that and tar mining automation status wasn't refreshed?

If not please add your .yafc project because on your synced mods and my project there are no issues.

**Comment by Emerassi** [comment] 2021-05-29 17:32
That was it.  I wasn't able to get a refresh by closing dependency explorer or Never Enough Items Explorer and re-opening them.  I was however able to get a refresh by saving, closing the application, and then re-opening it.  I got it working for Crude Oil, Natural Gas, and Tar and as a result so many things have changed in the solver.

On the other hand it now things I'm going to need 16.1G Tar for all science (is that billion?) so probably not going to be sourcing EVERYTHING from pumps.

Thank you for your help in debugging this issue.

**Comment by ShadowTheAge** [comment] 2021-05-29 22:29
Yes, G is a billion (Giga-). yeah, in py mining tar/oil isn't really an option, only for early game. It can produce about 6M max from a node (I think?), plus mining productivity? Yeah, good luck with that.

**Closed** 2021-06-13 04:24 UTC
Labels: bug
