### ISSUE TITLE
[BUG] Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by ShadowGlass0** [ShadowTheAge/yafc#83] opened 2020-11-16 00:23 UTC
YAFC 0.5.2
Factorio 1.0.0
Windows

Object reference not set to an instance of an object.

   at YAFC.MainScreen.FadeDrawer.CreateDownscaledImage() in C:\projects\YAFC\YAFC\Windows\MainScreen.cs:line 552
   at YAFC.MainScreen.<ShowPseudoScreen>b__56_0(Object x) in C:\projects\YAFC\YAFC\Windows\MainScreen.cs:line 438
   at YAFC.UI.Ui.ProcessAsyncCallbackQueue() in C:\projects\YAFC\YAFCui\Core\Ui.cs:line 223

[yafc_bug.zip](https://github.com/ShadowTheAge/yafc/files/5543417/yafc_bug.zip)

**Comment by ShadowGlass0** [comment] 2020-11-16 00:50
The folder where the projects were previously doesn't exist. After I've re-created the folder the bug was not happening.
A friendlier error message or auto-creating the missing folder would be nice.

**Comment by ShadowTheAge** [comment] 2020-11-16 08:52
Which folder exactly? Were you loading yafc without active project? (That is possible)
The problem is happening on the "Main screen" - that is the big screen with production tabs, etc.

**Comment by ShadowGlass0** [comment] 2020-11-16 10:53
It was the "Project file location", the first location on the welcome screen. I had used yafc before, and it seem it has remembered where my projects were. But that folder didn't exist anymore. I didn't look very closely and just clicked the blue button on the bottom "Create <project name>".

**Comment by ShadowTheAge** [comment] 2020-11-16 17:45
The error in the stacktrace was not caused by the missing directory. It is caused by a rare rendering bug. I have fixed it
I have added a message on missing directory also.

**Comment by ShadowTheAge** [comment] 2021-01-05 16:46
v0.5.4 has been released as a pre-release. I am closing the issue now, if your problem is not solved feel free to reopen it.

**Closed by ShadowTheAge** 2021-01-05 16:46 UTC
